//! Man page generation for mcp2cli alias applications.
//!
//! When `mcp2cli link create --name <alias>` is called, this module generates
//! a UNIX `man(1)` troff-formatted page and installs it alongside the symlink
//! so that `man <alias>` works immediately.
//!
//! The page is built from three sources:
//! 1. The named [`AppConfig`] — transport, endpoint, display name, profile.
//! 2. The cached [`CommandManifest`] (if available) — all tools, resources and
//!    prompts with their typed flags and descriptions.
//! 3. Hard-coded runtime commands (ls, doctor, inspect, jobs …) that are
//!    always present regardless of server capabilities.
//!
//! # Installation
//!
//! Man pages are written to a `man1/` subdirectory.  The default location
//! mirrors the XDG base-directory convention:
//!
//! ```text
//! ~/.local/share/man/man1/<alias>.1
//! ```
//!
//! Modern Linux `man-db` (Ubuntu/Debian) and macOS `man` both search
//! `~/.local/share/man` without extra configuration.  If the user installs
//! the symlink to a non-standard directory with `--dir`, they can supply
//! `--man-dir` to override the destination.
//!
//! # Format
//!
//! Output is `man(7)` troff/groff macro format — the same format used by
//! bash, git, curl, and virtually every other Unix CLI tool.  No external
//! crate is required; the macros are simple enough to emit directly.

use std::{
    fs,
    path::{Path, PathBuf},
};

use anyhow::{Context, Result};

use crate::{
    apps::manifest::{CommandKind, CommandManifest, ManifestEntry},
    config::AppConfig,
    mcp::model::TransportKind,
};

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Everything needed to produce a man page for one alias.
pub struct ManPageContext<'a> {
    /// The alias / symlink name (e.g. `work`).
    pub name: &'a str,
    /// The resolved application config for the alias.
    pub config: &'a AppConfig,
    /// Optional command manifest built from the cached discovery inventory.
    /// When `None`, the MCP commands section is omitted but built-in runtime
    /// commands are still documented.
    pub manifest: Option<&'a CommandManifest>,
}

/// Generate troff-formatted man page content as a `String`.
///
/// The returned string can be written directly to a `.1` file and read by
/// `man`, `nroff`, or `groff`.
pub fn generate(ctx: &ManPageContext<'_>) -> String {
    let mut out = String::new();

    let date = chrono::Utc::now().format("%B %Y").to_string(); // e.g. "March 2026"
    let version = env!("CARGO_PKG_VERSION");
    let name_upper = ctx.name.to_ascii_uppercase();

    // Display name: prefer profile overlay > manifest server_name > config display_name
    let display_name = ctx
        .config
        .profile
        .as_ref()
        .and_then(|p| p.display_name.as_deref())
        .or_else(|| ctx.manifest.and_then(|m| m.server_name.as_deref()))
        .unwrap_or(&ctx.config.server.display_name);

    // ---- Title header -------------------------------------------------------
    ln(
        &mut out,
        &format!(
            ".TH {} 1 \"{}\" \"mcp2cli {}\" \"MCP CLI Applications\"",
            name_upper, date, version
        ),
    );

    // ---- NAME ---------------------------------------------------------------
    section(&mut out, "NAME");
    ln(&mut out, &format!("{} \\- {}", ctx.name, esc(display_name)));

    // ---- SYNOPSIS -----------------------------------------------------------
    section(&mut out, "SYNOPSIS");
    ln(&mut out, ".nf");
    ln(&mut out, &format!(".B {}", ctx.name));
    ln(
        &mut out,
        "[\\fB--json\\fR] [\\fB--output\\fR \\fIFORMAT\\fR] [\\fB--timeout\\fR \\fISECS\\fR]",
    );
    ln(&mut out, "\\fICOMMAND\\fR [\\fICOMMAND\\-OPTIONS\\fR ...]");
    ln(&mut out, ".fi");

    // ---- DESCRIPTION --------------------------------------------------------
    section(&mut out, "DESCRIPTION");
    ln(
        &mut out,
        &format!(
            "\\fB{}\\fR is a dynamic MCP CLI application generated by \\fBmcp2cli\\fR(1), \
bound to the \\fI{}\\fR server.",
            ctx.name,
            esc(display_name)
        ),
    );
    ln(&mut out, ".PP");
    ln(
        &mut out,
        "MCP server tools become subcommands with typed \\fB--flags\\fR derived from JSON \
Schema. Resources are accessible via the \\fBget\\fR verb. Prompts become \
workflow subcommands.",
    );
    ln(&mut out, ".PP");

    // Transport details
    match &ctx.config.server.transport {
        TransportKind::StreamableHttp => {
            let endpoint = ctx.config.server.endpoint.as_deref().unwrap_or("(not set)");
            ln(
                &mut out,
                &format!(
                    "Transport: Streamable HTTP.  Endpoint: \\fI{}\\fR.",
                    esc(endpoint)
                ),
            );
        }
        TransportKind::Stdio => {
            let cmd = ctx
                .config
                .server
                .stdio
                .command
                .as_deref()
                .unwrap_or("(not set)");
            let args_str = ctx.config.server.stdio.args.join(" ");
            if args_str.is_empty() {
                ln(
                    &mut out,
                    &format!(
                        "Transport: Stdio subprocess.  Command: \\fI{}\\fR.",
                        esc(cmd)
                    ),
                );
            } else {
                ln(
                    &mut out,
                    &format!(
                        "Transport: Stdio subprocess.  Command: \\fI{} {}\\fR.",
                        esc(cmd),
                        esc(&args_str)
                    ),
                );
            }
        }
    }

    // ---- GLOBAL OPTIONS -----------------------------------------------------
    section(&mut out, "GLOBAL OPTIONS");
    tagged_para(
        &mut out,
        "\\fB--json\\fR",
        "Emit machine-readable JSON output instead of human-readable text. \
All commands honour this flag.",
    );
    tagged_para(
        &mut out,
        "\\fB--output\\fR \\fIFORMAT\\fR",
        "Output format. One of: \\fIhuman\\fR (default), \\fIjson\\fR, \\fIndjson\\fR.",
    );
    tagged_para(
        &mut out,
        "\\fB--timeout\\fR \\fISECS\\fR",
        "Per-request timeout in seconds. Overrides the value in the config file.",
    );
    tagged_para(
        &mut out,
        "\\fB--background\\fR",
        "Execute the command as a background job and return immediately with a job ID.",
    );
    tagged_para(
        &mut out,
        "\\fB--args-file\\fR \\fIPATH\\fR",
        "Load command arguments from a JSON file. Useful for commands with complex payloads.",
    );

    // ---- BUILT-IN COMMANDS (always present) ---------------------------------
    section(&mut out, "BUILT-IN COMMANDS");
    ln(
        &mut out,
        "These commands are available regardless of server capabilities.",
    );
    tagged_para(
        &mut out,
        "\\fBls\\fR [\\fB--json\\fR]",
        "Discover and list all server capabilities: tools, resources, and prompts. \
The output is cached locally for subsequent calls.",
    );
    tagged_para(
        &mut out,
        "\\fBdoctor\\fR [\\fB--json\\fR]",
        "Run connection and capability diagnostics. Reports transport health, protocol \
version, auth state, and cached capability status.",
    );
    tagged_para(
        &mut out,
        "\\fBinspect\\fR [\\fB--json\\fR]",
        "Show full server capabilities, negotiated protocol information, and metadata.",
    );
    tagged_para(
        &mut out,
        "\\fBget\\fR \\fIURI\\fR [\\fB--json\\fR]",
        "Read a server resource identified by URI.",
    );
    tagged_para(
        &mut out,
        "\\fBjobs list\\fR",
        "List all background jobs and their current status.",
    );
    tagged_para(
        &mut out,
        "\\fBjobs watch\\fR [\\fB--id\\fR \\fIID\\fR | \\fB--latest\\fR]",
        "Stream live status updates for a background job until it completes.",
    );
    tagged_para(
        &mut out,
        "\\fBjobs cancel\\fR [\\fB--id\\fR \\fIID\\fR | \\fB--latest\\fR]",
        "Request cancellation of a running background job.",
    );
    tagged_para(
        &mut out,
        "\\fBauth login\\fR",
        "Start the OAuth login flow for servers that require authentication.",
    );
    tagged_para(
        &mut out,
        "\\fBauth logout\\fR",
        "Clear stored authentication tokens.",
    );
    tagged_para(
        &mut out,
        "\\fBauth status\\fR",
        "Show current authentication state.",
    );

    // ---- MCP TOOLS, RESOURCES, PROMPTS (from cached manifest) --------------
    if let Some(manifest) = ctx.manifest {
        write_manifest_sections(&mut out, manifest);
    } else {
        section(&mut out, "MCP COMMANDS");
        ln(
            &mut out,
            "No cached capability inventory found. Run \\fBls\\fR to discover commands:",
        );
        ln(&mut out, ".PP");
        ln(&mut out, ".nf");
        ln(&mut out, &format!("    {} ls", ctx.name));
        ln(&mut out, ".fi");
        ln(&mut out, ".PP");
        ln(
            &mut out,
            "After discovery, re-run \\fBmcp2cli link create\\fR to regenerate this man page \
with full command documentation.",
        );
    }

    // ---- ENVIRONMENT --------------------------------------------------------
    section(&mut out, "ENVIRONMENT");
    tagged_para(
        &mut out,
        "\\fBMCP2CLI_CONFIG_DIR\\fR",
        "Override the directory where named configs are stored.",
    );
    tagged_para(
        &mut out,
        "\\fBMCP2CLI_DATA_DIR\\fR",
        "Override the directory for runtime state, tokens, and discovery cache.",
    );
    tagged_para(
        &mut out,
        "\\fBMCP2CLI_BIN_DIR\\fR",
        "Override the default symlink directory.",
    );
    tagged_para(
        &mut out,
        "\\fBMCP2CLI_TELEMETRY\\fR",
        "Set to \\fIoff\\fR, \\fI0\\fR, or \\fIfalse\\fR to disable telemetry.",
    );
    tagged_para(
        &mut out,
        "\\fBDO_NOT_TRACK\\fR",
        "Set to \\fI1\\fR to opt out of telemetry (https://consoledonottrack.com/).",
    );
    tagged_para(
        &mut out,
        "\\fBRUST_LOG\\fR",
        "Control log verbosity using tracing filter syntax, e.g. \\fImcp2cli=debug\\fR.",
    );

    // ---- FILES --------------------------------------------------------------
    section(&mut out, "FILES");
    tagged_para(
        &mut out,
        &format!("\\fI~/.local/bin/{}\\fR", ctx.name),
        "Symlink to the mcp2cli binary (default location).",
    );
    tagged_para(
        &mut out,
        &format!("\\fI~/.config/mcp2cli/configs/{}.yaml\\fR", ctx.name),
        "Named configuration file (default location).",
    );
    tagged_para(
        &mut out,
        &format!(
            "\\fI~/.local/share/mcp2cli/instances/{}/state.json\\fR",
            ctx.name
        ),
        "Persisted state: auth sessions, discovery cache, background jobs.",
    );
    tagged_para(
        &mut out,
        &format!("\\fI~/.local/share/man/man1/{}.1\\fR", ctx.name),
        "This man page (default location).",
    );

    // ---- SEE ALSO -----------------------------------------------------------
    section(&mut out, "SEE ALSO");
    ln(&mut out, ".BR mcp2cli (1),");
    ln(&mut out, ".BR man (1),");
    ln(&mut out, ".BR jq (1)");

    // ---- NOTES --------------------------------------------------------------
    section(&mut out, "NOTES");
    ln(
        &mut out,
        "MCP (Model Context Protocol) is an open standard developed by Anthropic that \
defines how AI models connect to tools and data sources. See \
\\fIhttps://modelcontextprotocol.io\\fR for the specification.",
    );
    ln(&mut out, ".PP");
    ln(
        &mut out,
        "\\fBmcp2cli\\fR is built at TSOK \\(em The Source of Knowledge AI Laboratory. \
Source code and documentation: \\fIhttps://github.com/mcp2cli/source-code\\fR.",
    );

    out
}

/// Write the generated page to `<man_dir>/<name>.1`.
///
/// The directory is created if it does not exist. Returns the full path to
/// the installed file.
pub fn install(name: &str, content: &str, man_dir: &Path) -> Result<PathBuf> {
    fs::create_dir_all(man_dir)
        .with_context(|| format!("failed to create man directory: {}", man_dir.display()))?;

    let page_path = man_dir.join(format!("{}.1", name));
    fs::write(&page_path, content)
        .with_context(|| format!("failed to write man page: {}", page_path.display()))?;

    Ok(page_path)
}

/// Generate the man page for the `mcp2cli` host binary itself.
///
/// This is distinct from [`generate`], which produces pages for alias
/// applications.  The host page documents config management, alias creation,
/// ad-hoc mode, and every host command.
pub fn generate_host() -> String {
    let mut out = String::new();
    let date = chrono::Utc::now().format("%B %Y").to_string();
    let version = env!("CARGO_PKG_VERSION");

    // ---- Title header -------------------------------------------------------
    ln(
        &mut out,
        &format!(
            ".TH MCP2CLI 1 \"{}\" \"mcp2cli {}\" \"MCP CLI Applications\"",
            date, version
        ),
    );

    // ---- NAME ---------------------------------------------------------------
    section(&mut out, "NAME");
    ln(
        &mut out,
        "mcp2cli \\- turn any MCP server into a native command-line application",
    );

    // ---- SYNOPSIS -----------------------------------------------------------
    section(&mut out, "SYNOPSIS");
    ln(&mut out, ".nf");
    ln(&mut out, ".B mcp2cli");
    ln(
        &mut out,
        "[\\fB--url\\fR \\fIURL\\fR | \\fB--stdio\\fR \\fICMD\\fR] \
[\\fB--json\\fR] [\\fB--no-telemetry\\fR]",
    );
    ln(&mut out, "\\fICOMMAND\\fR [\\fARGS\\fR]");
    ln(&mut out, ".fi");
    ln(&mut out, ".PP");
    ln(&mut out, ".B mcp2cli config init");
    ln(
        &mut out,
        "\\fB--name\\fR \\fINAME\\fR [\\fB--transport\\fR \\fIKIND\\fR] \
[\\fB--endpoint\\fR \\fIURL\\fR] [...]",
    );
    ln(&mut out, ".PP");
    ln(&mut out, ".B mcp2cli link create");
    ln(
        &mut out,
        "\\fB--name\\fR \\fINAME\\fR [\\fB--dir\\fR \\fIPATH\\fR] \
[\\fB--man-dir\\fR \\fIPATH\\fR] [\\fB--no-man\\fR] [\\fB--force\\fR]",
    );
    ln(&mut out, ".PP");
    ln(&mut out, ".B mcp2cli man install");
    ln(&mut out, "[\\fB--dir\\fR \\fIPATH\\fR]");

    // ---- DESCRIPTION --------------------------------------------------------
    section(&mut out, "DESCRIPTION");
    ln(
        &mut out,
        "\\fBmcp2cli\\fR is a universal CLI bridge for MCP (Model Context Protocol) servers. \
It auto-discovers server capabilities and maps them to typed terminal commands — \
tools become verbs, resources become nouns, prompts become workflows.",
    );
    ln(&mut out, ".PP");
    ln(&mut out, "There are two usage models:");
    ln(&mut out, ".TP");
    ln(&mut out, "Ad-hoc mode");
    ln(
        &mut out,
        "Point directly at a server with \\fB--url\\fR or \\fB--stdio\\fR. \
No configuration needed. Useful for quick exploration and CI scripts.",
    );
    ln(&mut out, ".TP");
    ln(&mut out, "Named config + alias mode");
    ln(
        &mut out,
        "Create a named config (\\fBmcp2cli config init\\fR), then create a symlink alias \
(\\fBmcp2cli link create\\fR). The alias behaves as a standalone application for \
that server: \\fBwork ls\\fR, \\fBprod doctor\\fR, \\fBstaging deploy\\fR.",
    );
    ln(&mut out, ".PP");
    ln(
        &mut out,
        "Server capabilities are discovered from the MCP JSON Schema. Each tool's \
\\fBinputSchema\\fR properties become typed \\fB--flags\\fR with validation, required-field \
enforcement, and enum constraints. Dotted tool names become nested subcommands.",
    );

    // ---- AD-HOC OPTIONS -----------------------------------------------------
    section(&mut out, "AD-HOC OPTIONS");
    tagged_para(
        &mut out,
        "\\fB--url\\fR \\fIURL\\fR",
        "Connect to an MCP server over Streamable HTTP at the given URL. \
Example: \\fBmcp2cli --url http://127.0.0.1:3001/mcp ls\\fR",
    );
    tagged_para(
        &mut out,
        "\\fB--stdio\\fR \\fICOMMAND\\fR",
        "Spawn a subprocess MCP server and communicate over stdin/stdout. \
Example: \\fBmcp2cli --stdio \"npx @modelcontextprotocol/server-everything\" ls\\fR",
    );

    // ---- GLOBAL OPTIONS -----------------------------------------------------
    section(&mut out, "GLOBAL OPTIONS");
    tagged_para(
        &mut out,
        "\\fB--json\\fR",
        "Emit machine-readable JSON output for all commands.",
    );
    tagged_para(
        &mut out,
        "\\fB--output\\fR \\fIFORMAT\\fR",
        "Output format: \\fIhuman\\fR (default), \\fIjson\\fR, or \\fIndjson\\fR.",
    );
    tagged_para(
        &mut out,
        "\\fB--config\\fR \\fINAME\\fR",
        "Explicitly select a named config to use for this invocation.",
    );
    tagged_para(
        &mut out,
        "\\fB--no-telemetry\\fR",
        "Disable telemetry collection for this invocation.",
    );

    // ---- HOST COMMANDS ------------------------------------------------------
    section(&mut out, "HOST COMMANDS");
    ln(
        &mut out,
        "Host commands manage the local configuration and alias estate. \
No server connection is required.",
    );

    ln(&mut out, ".SS config init");
    ln(&mut out, "Create a new named configuration file.");
    ln(&mut out, ".PP");
    ln(&mut out, ".nf");
    ln(&mut out, "mcp2cli config init --name \\fINAME\\fR \\\\");
    ln(
        &mut out,
        "  [--app \\fIPROFILE\\fR]  [--transport stdio|streamable_http] \\\\",
    );
    ln(
        &mut out,
        "  [--endpoint \\fIURL\\fR]  [--stdio-command \\fICMD\\fR] \\\\",
    );
    ln(&mut out, "  [--stdio-arg \\fIARG\\fR]...  [--force]");
    ln(&mut out, ".fi");
    ln(&mut out, ".TP");
    ln(&mut out, "\\fB--name\\fR \\fINAME\\fR");
    ln(
        &mut out,
        "Config identifier. Used to look up the config and name symlink aliases.",
    );
    ln(&mut out, ".TP");
    ln(&mut out, "\\fB--transport\\fR \\fIKIND\\fR");
    ln(
        &mut out,
        "One of \\fIstreamable_http\\fR (default) or \\fIstdio\\fR.",
    );
    ln(&mut out, ".TP");
    ln(&mut out, "\\fB--endpoint\\fR \\fIURL\\fR");
    ln(
        &mut out,
        "HTTP endpoint for Streamable HTTP transport (required for that transport).",
    );
    ln(&mut out, ".TP");
    ln(&mut out, "\\fB--stdio-command\\fR \\fICMD\\fR");
    ln(&mut out, "Subprocess command for Stdio transport.");
    ln(&mut out, ".TP");
    ln(&mut out, "\\fB--stdio-arg\\fR \\fIARG\\fR");
    ln(
        &mut out,
        "Additional argument(s) passed to the stdio subprocess. Repeatable.",
    );
    ln(&mut out, ".TP");
    ln(&mut out, "\\fB--force\\fR");
    ln(&mut out, "Overwrite an existing config with the same name.");

    ln(&mut out, ".SS config list");
    ln(&mut out, "List all named configurations.");

    ln(&mut out, ".SS config show");
    ln(
        &mut out,
        "Display the resolved settings for a named config.",
    );
    ln(&mut out, ".PP");
    ln(&mut out, ".nf");
    ln(&mut out, "mcp2cli config show --name \\fINAME\\fR");
    ln(&mut out, ".fi");

    ln(&mut out, ".SS link create");
    ln(
        &mut out,
        "Create a symlink alias for a named config. After creation, the alias can be \
invoked directly as a standalone CLI. A man page for the alias is also generated \
and installed automatically unless \\fB--no-man\\fR is given.",
    );
    ln(&mut out, ".PP");
    ln(&mut out, ".nf");
    ln(
        &mut out,
        "mcp2cli link create --name \\fINAME\\fR [--dir \\fIPATH\\fR] \\\\",
    );
    ln(&mut out, "  [--man-dir \\fIPATH\\fR] [--no-man] [--force]");
    ln(&mut out, ".fi");
    ln(&mut out, ".TP");
    ln(&mut out, "\\fB--name\\fR \\fINAME\\fR");
    ln(&mut out, "Name of the alias and the named config to bind.");
    ln(&mut out, ".TP");
    ln(&mut out, "\\fB--dir\\fR \\fIPATH\\fR");
    ln(
        &mut out,
        "Directory where the symlink is created (default: \\fI~/.local/bin\\fR).",
    );
    ln(&mut out, ".TP");
    ln(&mut out, "\\fB--man-dir\\fR \\fIPATH\\fR");
    ln(
        &mut out,
        "Directory where the alias man page is installed \
(default: \\fI~/.local/share/man/man1\\fR).",
    );
    ln(&mut out, ".TP");
    ln(&mut out, "\\fB--no-man\\fR");
    ln(
        &mut out,
        "Skip man page generation and installation for this alias.",
    );
    ln(&mut out, ".TP");
    ln(&mut out, "\\fB--force\\fR");
    ln(&mut out, "Replace an existing symlink at the target path.");

    ln(&mut out, ".SS use");
    ln(
        &mut out,
        "Set, show, or clear the active configuration. The active config is used when \
\\fBmcp2cli\\fR is invoked without an explicit config name.",
    );
    ln(&mut out, ".PP");
    ln(&mut out, ".nf");
    ln(&mut out, "mcp2cli use \\fINAME\\fR     # set active");
    ln(&mut out, "mcp2cli use --show         # show current active");
    ln(&mut out, "mcp2cli use --clear        # clear active");
    ln(&mut out, ".fi");

    ln(&mut out, ".SS man install");
    ln(
        &mut out,
        "Install (or refresh) the \\fBmcp2cli\\fR(1) man page for the host binary itself.",
    );
    ln(&mut out, ".PP");
    ln(&mut out, ".nf");
    ln(&mut out, "mcp2cli man install [--dir \\fIPATH\\fR]");
    ln(&mut out, ".fi");
    ln(&mut out, ".TP");
    ln(&mut out, "\\fB--dir\\fR \\fIPATH\\fR");
    ln(
        &mut out,
        "Target man1 directory (default: \\fI~/.local/share/man/man1\\fR).",
    );

    ln(&mut out, ".SS daemon start|stop|status");
    ln(
        &mut out,
        "Manage a background daemon that keeps the MCP session warm between invocations, \
eliminating cold-start latency.",
    );
    ln(&mut out, ".PP");
    ln(&mut out, ".nf");
    ln(&mut out, "mcp2cli daemon start --name \\fINAME\\fR");
    ln(&mut out, "mcp2cli daemon stop  --name \\fINAME\\fR");
    ln(&mut out, "mcp2cli daemon status [--name \\fINAME\\fR]");
    ln(&mut out, ".fi");

    // ---- RUNTIME COMMANDS ---------------------------------------------------
    section(&mut out, "RUNTIME COMMANDS");
    ln(
        &mut out,
        "Runtime commands require an active or named config (or ad-hoc \\fB--url\\fR / \
\\fB--stdio\\fR flags). They connect to the configured MCP server.",
    );
    tagged_para(
        &mut out,
        "\\fBls\\fR [\\fB--tools\\fR|\\fB--resources\\fR|\\fB--prompts\\fR] [\\fB--filter\\fR \\fIPATTERN\\fR]",
        "Discover and list server capabilities. Results are cached for offline use.",
    );
    tagged_para(
        &mut out,
        "\\fBping\\fR",
        "Send a ping to the server and report round-trip latency.",
    );
    tagged_para(
        &mut out,
        "\\fBdoctor\\fR",
        "Run diagnostics: transport, protocol version, auth state, capability cache.",
    );
    tagged_para(
        &mut out,
        "\\fBinspect\\fR",
        "Dump full server capabilities, negotiated session details, and metadata.",
    );
    tagged_para(
        &mut out,
        "\\fBget\\fR \\fIURI\\fR",
        "Read a server resource by URI.",
    );
    tagged_para(
        &mut out,
        "\\fBjobs list|show|wait|cancel|watch\\fR",
        "Manage background jobs started with \\fB--background\\fR.",
    );
    tagged_para(
        &mut out,
        "\\fBauth login|logout|status\\fR",
        "OAuth authentication management.",
    );
    tagged_para(
        &mut out,
        "\\fBsubscribe\\fR \\fIURI\\fR / \\fBunsubscribe\\fR \\fIURI\\fR",
        "Subscribe to or unsubscribe from server-pushed resource change notifications.",
    );
    tagged_para(
        &mut out,
        "\\fBlog\\fR \\fILEVEL\\fR",
        "Set the server-side log level (debug, info, warn, error).",
    );
    tagged_para(
        &mut out,
        "\\fBcomplete\\fR \\fIREF\\fR \\fINAME\\fR \\fIARG\\fR",
        "Request completion values from the server for a given argument.",
    );

    // ---- JSON OUTPUT --------------------------------------------------------
    section(&mut out, "JSON OUTPUT");
    ln(
        &mut out,
        "All commands support \\fB--json\\fR output. The envelope format is consistent \
across every command:",
    );
    ln(&mut out, ".PP");
    ln(&mut out, ".nf");
    ln(&mut out, "{");
    ln(&mut out, "  \"app_id\":  \"<alias-or-config-name>\",");
    ln(&mut out, "  \"command\": \"<command>\",");
    ln(&mut out, "  \"summary\": \"<one-line summary>\",");
    ln(&mut out, "  \"lines\":   [\"...\"],");
    ln(&mut out, "  \"data\":    { ... }");
    ln(&mut out, "}");
    ln(&mut out, ".fi");
    ln(&mut out, ".PP");
    ln(
        &mut out,
        "Pipe to \\fBjq\\fR(1) for filtering and transformation in scripts and agent loops.",
    );

    // ---- ENVIRONMENT --------------------------------------------------------
    section(&mut out, "ENVIRONMENT");
    tagged_para(
        &mut out,
        "\\fBMCP2CLI_CONFIG_DIR\\fR",
        "Directory for named config files (default: \\fI~/.config/mcp2cli\\fR).",
    );
    tagged_para(
        &mut out,
        "\\fBMCP2CLI_DATA_DIR\\fR",
        "Directory for state files, token stores, and discovery cache \
(default: \\fI~/.local/share/mcp2cli\\fR).",
    );
    tagged_para(
        &mut out,
        "\\fBMCP2CLI_BIN_DIR\\fR",
        "Default directory for symlink aliases (default: \\fI~/.local/bin\\fR).",
    );
    tagged_para(
        &mut out,
        "\\fBMCP2CLI_CONFIG\\fR",
        "Path to an explicit config file, bypassing named-config lookup.",
    );
    tagged_para(
        &mut out,
        "\\fBMCP2CLI_TELEMETRY\\fR",
        "Set to \\fIoff\\fR, \\fI0\\fR, or \\fIfalse\\fR to disable telemetry.",
    );
    tagged_para(
        &mut out,
        "\\fBDO_NOT_TRACK\\fR",
        "Set to \\fI1\\fR to opt out of telemetry (https://consoledonottrack.com/).",
    );
    tagged_para(
        &mut out,
        "\\fBRUST_LOG\\fR",
        "Tracing filter for log output, e.g. \\fImcp2cli=debug\\fR.",
    );

    // ---- FILES --------------------------------------------------------------
    section(&mut out, "FILES");
    tagged_para(
        &mut out,
        "\\fI~/.config/mcp2cli/configs/<name>.yaml\\fR",
        "Named configuration files.",
    );
    tagged_para(
        &mut out,
        "\\fI~/.local/share/mcp2cli/host/active-config.json\\fR",
        "Active config selection.",
    );
    tagged_para(
        &mut out,
        "\\fI~/.local/share/mcp2cli/instances/<name>/state.json\\fR",
        "Per-config state: auth sessions, discovery inventory, background jobs.",
    );
    tagged_para(
        &mut out,
        "\\fI~/.local/share/mcp2cli/telemetry.ndjson\\fR",
        "Local telemetry event log.",
    );
    tagged_para(
        &mut out,
        "\\fI~/.local/bin/<alias>\\fR",
        "Symlink aliases created by \\fBlink create\\fR.",
    );
    tagged_para(
        &mut out,
        "\\fI~/.local/share/man/man1/mcp2cli.1\\fR",
        "This man page (default install location).",
    );
    tagged_para(
        &mut out,
        "\\fI~/.local/share/man/man1/<alias>.1\\fR",
        "Man pages generated for alias applications.",
    );

    // ---- EXAMPLES -----------------------------------------------------------
    section(&mut out, "EXAMPLES");
    ln(&mut out, ".SS Ad-hoc usage (zero config)");
    ln(&mut out, ".nf");
    ln(&mut out, "# HTTP server");
    ln(&mut out, "mcp2cli --url http://127.0.0.1:3001/mcp ls");
    ln(
        &mut out,
        "mcp2cli --url http://127.0.0.1:3001/mcp echo --message hello",
    );
    ln(&mut out, "");
    ln(&mut out, "# Stdio server");
    ln(
        &mut out,
        "mcp2cli --stdio \"npx @modelcontextprotocol/server-everything\" ls",
    );
    ln(&mut out, ".fi");

    ln(&mut out, ".SS Named config + alias");
    ln(&mut out, ".nf");
    ln(&mut out, "mcp2cli config init --name work \\\\");
    ln(&mut out, "  --transport streamable_http \\\\");
    ln(&mut out, "  --endpoint http://127.0.0.1:3001/mcp");
    ln(&mut out, "");
    ln(&mut out, "mcp2cli link create --name work");
    ln(&mut out, "");
    ln(&mut out, "work ls");
    ln(&mut out, "work echo --message hello");
    ln(&mut out, "work --json doctor | jq '.data.server'");
    ln(&mut out, ".fi");

    ln(&mut out, ".SS Multi-server setup");
    ln(&mut out, ".nf");
    ln(
        &mut out,
        "mcp2cli config init --name dev   --transport stdio \\\\",
    );
    ln(&mut out, "  --stdio-command ./dev-server");
    ln(
        &mut out,
        "mcp2cli config init --name prod  --transport streamable_http \\\\",
    );
    ln(&mut out, "  --endpoint https://prod.api/mcp");
    ln(&mut out, "");
    ln(&mut out, "mcp2cli link create --name dev");
    ln(&mut out, "mcp2cli link create --name prod");
    ln(&mut out, "");
    ln(&mut out, "dev ls");
    ln(&mut out, "prod doctor");
    ln(&mut out, "prod deploy --version 2.1.0 --background");
    ln(&mut out, "prod jobs watch --latest");
    ln(&mut out, ".fi");

    ln(&mut out, ".SS JSON pipeline");
    ln(&mut out, ".nf");
    ln(&mut out, "work --json ls | jq '.data.items[].id'");
    ln(
        &mut out,
        "work --json echo --message hi | jq '.data.content[0].text'",
    );
    ln(&mut out, ".fi");

    // ---- SEE ALSO -----------------------------------------------------------
    section(&mut out, "SEE ALSO");
    ln(&mut out, ".BR man (1),");
    ln(&mut out, ".BR jq (1),");
    ln(&mut out, ".BR cargo (1)");

    // ---- NOTES --------------------------------------------------------------
    section(&mut out, "NOTES");
    ln(
        &mut out,
        "MCP (Model Context Protocol) is an open standard developed by Anthropic. \
Full specification at \\fIhttps://modelcontextprotocol.io\\fR.",
    );
    ln(&mut out, ".PP");
    ln(
        &mut out,
        "\\fBmcp2cli\\fR is built at TSOK \\(em The Source of Knowledge AI Laboratory. \
Source code and documentation: \\fIhttps://github.com/mcp2cli/source-code\\fR.",
    );

    out
}

fn write_manifest_sections(out: &mut String, manifest: &CommandManifest) {
    // Separate commands by kind
    let mut tools: Vec<(&String, &crate::apps::manifest::ManifestCommand)> = Vec::new();
    let mut resources: Vec<(&String, &crate::apps::manifest::ManifestCommand)> = Vec::new();
    let mut prompts: Vec<(&String, &crate::apps::manifest::ManifestCommand)> = Vec::new();
    let mut groups: Vec<(
        &String,
        &str,
        &indexmap::IndexMap<String, crate::apps::manifest::ManifestCommand>,
    )> = Vec::new();

    for (name, entry) in &manifest.commands {
        match entry {
            ManifestEntry::Command(cmd) => match cmd.kind {
                CommandKind::Tool => tools.push((name, cmd)),
                CommandKind::Resource | CommandKind::ResourceTemplate => {
                    resources.push((name, cmd))
                }
                CommandKind::Prompt => prompts.push((name, cmd)),
            },
            ManifestEntry::Group { summary, children } => {
                groups.push((name, summary.as_str(), children));
            }
        }
    }

    if !tools.is_empty() || !groups.is_empty() {
        section(out, "MCP TOOLS");
        ln(
            out,
            "Tools exposed by the MCP server. Each tool becomes a subcommand with typed flags.",
        );
        for (name, cmd) in &tools {
            write_command(out, name, cmd, 0);
        }
        for (gname, gsummary, children) in &groups {
            ln(out, ".TP");
            ln(out, &format!("\\fB{}\\fR", gname));
            ln(out, &format!("{} (command group)", esc(gsummary)));
            for (cname, ccmd) in *children {
                write_command(out, &format!("{} {}", gname, cname), ccmd, 1);
            }
        }
    }

    if !resources.is_empty() {
        section(out, "MCP RESOURCES");
        ln(
            out,
            "Resources exposed by the MCP server. Access with the \\fBget\\fR verb.",
        );
        for (name, cmd) in &resources {
            write_command(out, name, cmd, 0);
        }
    }

    if !prompts.is_empty() {
        section(out, "MCP PROMPTS");
        ln(out, "Prompt templates exposed by the MCP server.");
        for (name, cmd) in &prompts {
            write_command(out, name, cmd, 0);
        }
    }
}

fn write_command(
    out: &mut String,
    name: &str,
    cmd: &crate::apps::manifest::ManifestCommand,
    indent: usize,
) {
    let indent_str = if indent > 0 { ".RS 4\n" } else { "" };
    let dedent_str = if indent > 0 { ".RE\n" } else { "" };

    if !indent_str.is_empty() {
        ln(out, ".RS 4");
    }

    // Build synopsis line with flags
    let mut synopsis = format!("\\fB{}\\fR", name);
    for (flag_name, flag) in &cmd.flags {
        let meta = flag.flag_type.value_name();
        if flag.required {
            if meta.is_empty() {
                synopsis.push_str(&format!(" \\fB--{}\\fR", flag_name));
            } else {
                synopsis.push_str(&format!(" \\fB--{}\\fR \\fI{}\\fR", flag_name, meta));
            }
        } else if meta.is_empty() {
            synopsis.push_str(&format!(" [\\fB--{}\\fR]", flag_name));
        } else {
            synopsis.push_str(&format!(" [\\fB--{}\\fR \\fI{}\\fR]", flag_name, meta));
        }
    }
    if let Some(pos) = &cmd.positional {
        if pos.required {
            synopsis.push_str(&format!(" \\fI{}\\fR", pos.name.to_ascii_uppercase()));
        } else {
            synopsis.push_str(&format!(" [\\fI{}\\fR]", pos.name.to_ascii_uppercase()));
        }
    }
    if cmd.supports_background {
        synopsis.push_str(" [\\fB--background\\fR]");
    }

    ln(out, ".TP");
    ln(out, &synopsis);

    // Description
    if cmd.summary.is_empty() {
        ln(out, "(no description)");
    } else {
        ln(out, &esc(&cmd.summary));
    }

    // Per-flag documentation (only if there are flags with descriptions)
    let flags_with_docs: Vec<_> = cmd
        .flags
        .iter()
        .filter(|(_, f)| f.help.is_some() || f.enum_values.is_some() || f.default.is_some())
        .collect();

    if !flags_with_docs.is_empty() {
        ln(out, ".RS 4");
        for (flag_name, flag) in &flags_with_docs {
            let meta = flag.flag_type.value_name();
            let flag_label = if meta.is_empty() {
                format!("\\fB--{}\\fR", flag_name)
            } else {
                format!("\\fB--{}\\fR \\fI{}\\fR", flag_name, meta)
            };
            ln(out, ".TP");
            ln(out, &flag_label);
            let mut desc = flag
                .help
                .as_deref()
                .map(esc)
                .unwrap_or_else(|| String::new());
            if let Some(ref vals) = flag.enum_values {
                let joined = vals.join(", ");
                if desc.is_empty() {
                    desc = format!("One of: {}.", esc(&joined));
                } else {
                    desc.push_str(&format!("  One of: {}.", esc(&joined)));
                }
            }
            if let Some(ref default) = flag.default {
                desc.push_str(&format!(
                    "  Default: \\fI{}\\fR.",
                    esc(&default.to_string())
                ));
            }
            if flag.required {
                desc.push_str("  \\fB(required)\\fR");
            }
            if desc.is_empty() {
                ln(out, "(no description)");
            } else {
                ln(out, &desc);
            }
        }
        ln(out, ".RE");
    }

    if !dedent_str.is_empty() {
        ln(out, ".RE");
    }
    let _ = indent_str; // suppress unused warning
}

// ---------------------------------------------------------------------------
// Internal helpers — troff emission
// ---------------------------------------------------------------------------

/// Append a single line (with trailing newline) to the output buffer.
fn ln(out: &mut String, text: &str) {
    out.push_str(text);
    out.push('\n');
}

/// Emit a `.SH` section heading.
fn section(out: &mut String, name: &str) {
    ln(out, &format!(".SH {}", name));
}

/// Emit a `.TP` tagged paragraph: label on one line, text on the next.
fn tagged_para(out: &mut String, label: &str, text: &str) {
    ln(out, ".TP");
    ln(out, label);
    ln(out, text);
}

/// Escape text for safe inclusion in troff output.
///
/// Rules:
/// - Leading `.` or `'` on a line would be interpreted as a troff macro — prefix with `\&`.
/// - Backslash `\` must be doubled to `\\`.
/// - Hyphens that are meant as minus signs should use `\-` (renders correctly
///   in terminals and PDFs), but we keep plain `-` for flag names used in the
///   `--flag` synopsis and use `\-` only in paragraph body text.
fn esc(text: &str) -> String {
    let mut result = String::with_capacity(text.len() + 8);
    for line in text.split('\n') {
        if !result.is_empty() {
            result.push('\n');
        }
        // Escape backslashes first
        let escaped = line.replace('\\', "\\\\");
        // Prevent leading . or ' from being treated as macros
        if escaped.starts_with('.') || escaped.starts_with('\'') {
            result.push_str("\\&");
            result.push_str(&escaped);
        } else {
            result.push_str(&escaped);
        }
    }
    result
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::AppConfig;
    use crate::mcp::model::TransportKind;

    fn http_config(name: &str, endpoint: &str) -> AppConfig {
        let mut cfg = AppConfig::default();
        cfg.server.display_name = format!("{} Server", name);
        cfg.server.transport = TransportKind::StreamableHttp;
        cfg.server.endpoint = Some(endpoint.to_owned());
        cfg
    }

    fn stdio_config(name: &str, cmd: &str) -> AppConfig {
        let mut cfg = AppConfig::default();
        cfg.server.display_name = format!("{} Server", name);
        cfg.server.transport = TransportKind::Stdio;
        cfg.server.stdio.command = Some(cmd.to_owned());
        cfg
    }

    #[test]
    fn generate_http_no_manifest() {
        let config = http_config("work", "http://localhost:3001/mcp");
        let ctx = ManPageContext {
            name: "work",
            config: &config,
            manifest: None,
        };
        let page = generate(&ctx);

        // Title header
        assert!(page.contains(".TH WORK 1"), "missing title header");
        // NAME section
        assert!(page.contains(".SH NAME"), "missing NAME section");
        assert!(page.contains("work \\- "), "missing name line");
        // Transport
        assert!(
            page.contains("Streamable HTTP"),
            "missing transport description"
        );
        assert!(page.contains("localhost:3001"), "missing endpoint in page");
        // Built-in commands
        assert!(page.contains("\\fBls\\fR"), "missing ls");
        assert!(page.contains("\\fBdoctor\\fR"), "missing doctor");
        // No manifest notice
        assert!(
            page.contains("No cached capability inventory"),
            "missing no-manifest notice"
        );
        // SEE ALSO
        assert!(page.contains("mcp2cli (1)"), "missing see also");
    }

    #[test]
    fn generate_stdio_no_manifest() {
        let config = stdio_config("myapp", "./my-server");
        let ctx = ManPageContext {
            name: "myapp",
            config: &config,
            manifest: None,
        };
        let page = generate(&ctx);

        assert!(page.contains(".TH MYAPP 1"));
        assert!(page.contains("Stdio subprocess"));
        assert!(page.contains("./my-server"));
    }

    #[test]
    fn escape_dots_and_backslashes() {
        assert_eq!(esc(".foo"), "\\&.foo");
        assert_eq!(esc("a\\b"), "a\\\\b");
        assert_eq!(esc("normal"), "normal");
        assert_eq!(esc("'quoted"), "\\&'quoted");
    }

    #[test]
    fn install_creates_file() {
        let dir = tempfile::tempdir().unwrap();
        let man_dir = dir.path().join("man1");
        let content = ".TH TEST 1\n.SH NAME\ntest \\- placeholder\n";
        let path = install("test", content, &man_dir).unwrap();
        assert_eq!(path, man_dir.join("test.1"));
        assert_eq!(fs::read_to_string(&path).unwrap(), content);
    }

    #[test]
    fn install_creates_dir_if_missing() {
        let dir = tempfile::tempdir().unwrap();
        let nested = dir.path().join("a/b/c/man1");
        let path = install("cmd", "content", &nested).unwrap();
        assert!(path.exists());
    }
}
